### ISSUE TITLE
AMS 0.10 rc3 doesn't implement to_json on serializer correctly?

### ISSUE THREAD

**Issue by edude03** [rails-api/active_model_serializers#1367] opened 2015-12-08 22:03 UTC
I've fairly familiar with AMS 0.8 so for this project I decided to try 0.10

In 0.8 to use a serializer without render I would do
```
PostSerializer.new(@post).to_json
```
And I would get
```
{
 "id": 123
 "title": "some post"
}
```

I just tried the same thing with 0.10 RC3 and instead got

```
{ "object": 
  {
   "id": 123
   "title": "some post"  
  }
}
```

After digging in the source I found that ```SerializableResource.new ...``` is the new recommended way to do this however since `get_serializer_for` users class name + serializer and my serializer is namespace this doesn't work (passing the serializer in the options fixes this of course) 

However it seems to me that if I already have an instance of the serializer like in the primary example it should return the same thing that SerializableResource.to_json does? 

I'm not sure if this intended behaviour or a bug.

**Comment by bf4** [comment] 2015-12-09 04:01
It's not a bug. The JSON library in Ruby mixes in `to_json` but we should probably make it raise an exception.

**Comment by bf4** [comment] 2015-12-09 04:05
Accidentally hit enter, though somehow it still sorta makes sense:

It's not a bug. The JSON library in Ruby mixes in methods into Object such as `to_json`.

The job of the serializer is just to represent the serialization of the model/record you pass it.  You can see this by calling `attributes` on your instantiated serializer.  The adapter is what we can to_json.  This was kind of confusing and convoluted, which partly why there's a SerializableResource (also so you can do it outside of the controller easily).

To avoid this confusion,  we should probably make calling these methods on the serializer raise an exception. That could be a nice PR.

Also, you may be interested in https://github.com/rails-api/active_model_serializers/blob/master/docs/ARCHITECTURE.md

**Comment by bf4** [comment] 2015-12-09 04:06
I'm going to close this, but feel free to ask any questions.  And if you can help us with our 0.8 -> 0.10 upgrade docs, that'd be fantastic! See https://github.com/rails-api/active_model_serializers/issues/1005

**Closed by bf4** 2015-12-09 04:06 UTC
