### ISSUE TITLE
Fragment Caching + ActiveModel::Serializer::Type

### ISSUE THREAD

**Issue by bdmac** [rails-api/active_model_serializers#1457] opened 2016-01-22 17:34 UTC
I am using the `type` class method provided by `ActiveModel::Serializer::Type` to override the type for a certain serializer. This works fine with normal AMS caching. As soon as I add the `except` keyword on my cache call (triggering Fragment Caching), the class-level type setting in my serializer gets ignored and it reverts to inferring the type from the serialized object's class.

This does not seem to be expected behavior. I am trying to dig into FragmentCache adapter (I was surprised this was an adapter) to see what is going on. It looks like we dynamically create cached and non-cached serializers when fragment caching is invoked and my current best guess without having completed my investigation is that the class attribute `type` sets on the actual serializer is not being pulled forward into the generated fragment cache serializers... but I'm not sure yet.

**Comment by bdmac** [comment] 2016-01-22 17:39
I believe I could fix this by modifying FragmentCache around L#97 to be:
```ruby
cached.constantize.cache(klass._cache_options)
cached.constantize.type(klass._type)
```
The first line is already there to proxy forward the _cache_options but that is the only internal setting that is handled. I also see a few other possible problems similar to `type` that use `serializer.class_attribute`:

- _reflections
- _attributes_data
- _links

**Comment by bdmac** [comment] 2016-01-22 17:41
Do not see a clean way to ensure that any serializer DSL settings such as `type` are brought forward in FragmentCache since none of them are setting any kind of common structure. If they were all being merged into something like `dsl_options` or whatever then we could set that on the cached serializer in FragmentCache.

**Comment by bdmac** [comment] 2016-01-22 17:59
Actually the above almost works but not quite because I guess we wind up using `deep_merge` which is order dependent as to which hash's values win. Options seem to be either set it on both the cached and non-cached serializers OR only set it on the non-cached serializer which feels arbitrary.

**Comment by bdmac** [comment] 2016-01-22 18:15
Another, perhaps more "correct" solution is to have the dynamic cached/non-cached classes that FragmentCache creates be based on the serializer being cached instead of just "ActiveModel::Serializer". This would remove the need to copy any of the class variables over like we are doing today.
```ruby
          Object.const_set cached, Class.new(ActiveModel::Serializer) unless Object.const_defined?(cached)
          Object.const_set non_cached, Class.new(ActiveModel::Serializer) unless Object.const_defined?(non_cached)
```
becomes
```ruby
          Object.const_set cached, Class.new(klass) unless Object.const_defined?(cached)
          Object.const_set non_cached, Class.new(klass) unless Object.const_defined?(non_cached)
```
I don't see a any immediate drawback to this and it seems more correct. This would remove the need to pass forward the the `cache_options` which was already happening and prevent us from needing to pass `_type` and the others around as well.

**Comment by bdmac** [comment] 2016-01-22 19:32
I have a fix for this in #1458

**Comment by beauby** [comment] 2016-01-24 21:17
Thanks for looking into this @bdmac. I believe caching is indeed not in sync with the latest features added to AMS. I'm a bit busy currently but just wanted to let you know that I'll review #1458 asap.

**Comment by beauby** [comment] 2016-04-20 00:29
#1458 seemd to have been merged. @bdmac, can you confirm the issue is resolved?

**Closed** 2020-05-29 02:50 UTC
Labels: S: Bug, V: 0.10.x
