### ISSUE TITLE
How do you embed a relation instead of a link

### ISSUE THREAD

**Issue by bsylvain** [rails-api/active_model_serializers#2303] opened 2018-11-28 08:23 UTC
#### Expected behavior vs actual behavior
Here is how relations in my current invoice payload look like : 

`operations":{"data":[{"id":"5","type":"invoice/operation"}]}`

Here is what I would like to have : 

`operations":{"data":[{"id":"5","attributes":{"state":"payment","payment-type":""}}]}`

#### Steps to reproduce
My serializer use the following relation : 
```

class InvoicetSerializer < ActiveModel::Serializer
attributes :id,:automatic, #.... All the field

has_many :operations,serializer: OperationSerializer

```

#### Environment

ActiveModelSerializers Version 0.10.7

#### Additonal helpful information

I tried to include the relation in the AR query, `:serializer` ans `:each_serializer` options, to add `include=operation` to the query,

**Comment by bf4** [comment] 2018-11-29 04:08
Duplicate of https://github.com/rails-api/active_model_serializers/issues/2302

**Comment by bf4** [comment] 2018-11-29 04:12
See answer there.  You can mangle AMS to do that but it won't be jsonapi spec anymore.

In any case, since you know ams jsonapi supports the include param and I am guessing it is having no effect , maybe you have mistyped it? Maybe it should be plural like the relation?

**Closed by bf4** 2018-11-29 04:12 UTC
