### ISSUE TITLE
Infinite loop in circular associations

### ISSUE THREAD

**Issue by heartsentwined** [rails-api/active_model_serializers#211] opened 2013-02-20 12:04 UTC
`active_model_serializers` can handle self-referencing associations fine, e.g. `categories`, but it will run into an infinite loop if you try to sideload circular associations. An example is the twitter-esque `follower`-`followed` association pair.

```rb
class BaseSerializer < ActiveModel::Serializer
  embed :ids, include: true
end

class FollowerSerializer < BaseSerializer
  has_many :followeds
end

class FollowedSerializer < BaseSerializer
  has_many :followers
end
```

Let's say you start by requesting a `follower`. `active_model_serializers` will traverse its `followeds`, sideload the `followed` models by initiating a new `FollowedSerializer` for each, and if any `followed` points back to the original `follower` via its own `has_many :followers` association, we have an infinite loop.

The current workaround is, unfortunately, disable sideloading entirely for the offending associations.

```rb
class BaseSerializer < ActiveModel::Serializer
  embed :ids, include: true
end

class FollowerSerializer < BaseSerializer
  has_many :followeds, embed: :ids, include: false
end

class FollowedSerializer < BaseSerializer
  has_many :followers, embed: :ids, include: false
end
```

Perhaps keeping track of the model + primary key while loading associations (recursively) can solve this issue? This way the same model will only be serialized once.

**Comment by caspyin** [comment] 2015-01-13 00:30
Does #722 fix this same issue? It changes `lib/active_model/serializer/adapter/json_api.rb` where @colby-swandale changes `lib/active_model/serializer/associations.rb`. I'm not familiar enough with the inner workings of this project to know for sure.

#722 has already been pulled into master so if it does fix this issue, it would be nice to have it applied to 0.8.x and 0.9.x branches.

**Comment by ggordon** [comment] 2015-01-14 12:32
@caspyin #722 is specifically for the json-api adapter in master so it's not applicable to 0.8 or 0.9 branches.

**Comment by caspyin** [comment] 2015-01-14 18:09
@ggordon Ah ok, thanks for clarifying.

**Comment by kurko** [comment] 2015-01-21 21:33
@caspyin could you open a PR? I'd me happy to merge :)

**Comment by caspyin** [comment] 2015-01-23 21:34
@kurko You might look at @colby-swandale. He has a fork with a solution 2e791b6 for this already. @colby-swandale consider updating your fork and issuing a PR?

**Comment by evolve2k** [comment] 2015-01-31 00:53
Wow, we're almost at a two year anniversary on this issue, having been open back on 20 Feb 2013.
It's obviously affecting a lot of people, Im sure it's hairy, but would be awesome if it could be resolved.

I'm laying down the gauntlet, the challenge is to get this resolved before it hits two years old on 20 February 2015.

It's a 20 day challenge. Massive props to anyone who can help get this sorted.

**Comment by colby-swandale** [comment] 2015-01-31 11:58
I spent a few hours today to do a bit of an analysis to see if i could get any progress on this. There are a number problems with the design of the gem that is going to make this difficult to fix. 

The biggest problem is keeping track of what associations are made with what serializes. I have a patch that makes every serializer have a reference to the instance of its parent serializer so i have a trace of what serializers are related to what, but i cannot do this for the first serializer. Its initialized differently and its the only roadblock i have from having a good solution to this problem. Is anyone else working on this? maybe we could work together on this.

**Comment by j4rs** [comment] 2015-03-17 18:06
Why don't just use the relationship-attribute to access the object it belongs to?. In the example a comment access the post it belongs to using the attribute **post** avoiding the has_one:
```ruby
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :text
  has_many :comments
end

class CommentSerializer < ActiveModel::Serializer
  attributes :id, :title, :text, :post
end
```

**Comment by chrisccerami** [comment] 2015-04-26 04:06
Crazy this still hasn't been solved. I'm using the multiple serializers workaround, but I'd still love to see this fixed as I think overall AMS is a great tool.

**Comment by daino3** [comment] 2015-05-27 16:17
+1 for @j4rs solution which works for me, but feels... awkward...

**Comment by unpatioli** [comment] 2015-06-06 16:16
+1 @j4rs

**Comment by saneshark** [comment] 2015-06-08 20:16
I did something like this in 0.9 branch: 

```ruby
  def initialize(object, options={})
    self.class.has_one(:event) unless options[:exclude_event]
    super
  end
```
But technically you could do `object.association(:association_name).loaded?` I would think just as well.

**Comment by wallaceicy06** [comment] 2015-07-20 16:34
I just wanted to chime in and say I had a very difficult time dealing with this issue. I understand why stack depth becomes a problem for serializers that include their collections from their many-to-many relationships. What I don't understand is why the stack explodes when I choose to **not include** the collections at all.

For example:

```ruby
class JackSerializer < ActiveModel::Serializer
  attributes :id, :name
  has_many :users, include: false, embed: :id
end

class UserSerializer < ActiveModel::Serializer
  attributes :id, :username, :first_name, :last_name
  has_many :jacks, include: false, embed: :id
end
```

These associations cause an infinite recursion loop, and I don't understand why that should be a problem. If neither of these is embedding the other (except for the id), why would the serializer feel the need to make a recursive serialization call to the other? The generated JSON for one of these would look something like the following

```js
{
  user: {
    id: 1
    username: "joeblow"
    first_name: "Joe"
    last_name: "Blow"
    jack_ids: [1]
      0:  1
  }
}
```

Nowhere in that JSON does the serializer need to make a recursive serialization step to serialize the "jack" object. Yet the library still appears to be doing this.

**Comment by joaomdmoura** [comment] 2015-07-21 05:58
@wallaceicy06 we have being really focused on the new 0.10.x version. btw I would totally recommend you to check it out and give it a try, it is being wrote from the scratch. We already have a RC2 and you can also give master a try :smile:

We know there are some important issues on older versions of AMS, and we want to help you to fix it, but more important than that we also want to finish the new version.

Could you described which version of AMS, Ruby and Rails are you using? It will help us when trying to replicate the error in the future.

**Comment by wallaceicy06** [comment] 2015-07-21 06:19
@joaomdmoura I actually have a workaround using a custom serializer like mentioned above, so it's "fixed". I will check out master for sure. Keep up the great work, as this is an awesome gem!

I am on Rails 4.2.1 and AMS 0.9.3.

**Comment by joaomdmoura** [comment] 2015-07-26 14:57
Awesome! Great, in case of any problems just let us know, you can also use the [new docs](https://github.com/rails-api/active_model_serializers/tree/master/docs), it's not that big yet, but we are working on it.

**Comment by NullVoxPopuli** [comment] 2015-09-14 14:02
this is solved on master, via a new `include` options, where you define the nested associations.
Side loading is coming later this week.

**Comment by NullVoxPopuli** [comment] 2016-03-08 19:51
Closing, as using include prevents infinite looping.

**Closed by NullVoxPopuli** 2016-03-08 19:51 UTC
Labels: Bug, V: 0.9.x

**Comment by hcarreras** [comment] 2016-09-07 08:40
So, to be clear: ams 0.9 still has this bug and we have to upgrade to ams 1.0?
I'm currently using ams 0.9 and I can't upgrade since I use Rails 3.2.

**Comment by kapilsdv** [comment] 2016-12-14 11:03
Hi,
My code just get into one infinite loop using **AMS 0.10.0.**
```ruby
class OrganizationSerializer < ActiveModel::Serializer
  has_many :groups
end
```

```ruby
class GroupSerializer < ActiveModel::Serializer
  belongs_to :organization
end
```

```ruby
class GroupInviteSerializer < ActiveModel::Serializer
  attributes :join_requests

  belongs_to :group

  def join_requests
    ActiveModelSerializers::SerializableResource.new(object.group_invites.private_requests, {adapter: :json}).as_json
  end
end
```
_Note: I used adapter: :json, while my default configured adapter is :json_api._

_**private_requests** in object.group_invites.private_requests is just a scope that filters out group_invites on some basis (the scope works fine)._

I get in to the loop when i just render the organization that includes group
```ruby
render json: current_user.organization, include: ['picture,groups'], status: :ok
```
However if i doesn't pass the **options = {adapter: :json}** in the join_requests, it works fine

_Note: Also i haven't used GroupInviteSerializer because i have a custom attribute that find the group name of the invite and that raises **The method .group() must contain arguments** error._

Is this the expected behaviour?

**Comment by beauby** [comment] 2016-12-14 11:06
@kapilsdv Seems like expected behavior, as the JSON API adapter represents your data graph via its adjacency lists, whereas the JSON one does not (which implies that a data graph with oriented cycles does not have a defined representation with the JSON adapter).

**Comment by kapilsdv** [comment] 2016-12-14 11:12
@beauby Thanks for the quick reply.
I was just setting the :json adapter because it was rendering all the relationships with it also and I doesn't want them. I there any other options to **mute** the relationships data with SerializableResource or Serializer ?

**Comment by beauby** [comment] 2016-12-14 16:38
@kapilsdv There is some `include_linkage :if_sideloaded` option I think.

**Comment by bf4** [comment] 2016-12-15 02:35
@kangkyu Please open a new issue if you need additional discussion.
