### ISSUE TITLE
root is rendered inside a collection instead of labeling the collection

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1779] opened 2016-06-06 22:38 UTC
#### Expected behavior vs actual behavior

``` ruby
    render json:            objects.page(params[:page]).per(params[:per_page]), 
           each_serializer: nil, 
           root:            root&.pluralize
```

``` ruby
    [{"questions":{"id":1,"title":"eu4zUKCsWE4gLWsUuzWo","company_id":1,"created_at":"2016-06-06T15:30:59.000-07:00","updated_at":"2016-06-06T15:30:59.000-07:00","deleted_at":null,"reference_id":null}}]
```

it seems if `each_serializer` is given a nil, then I get this kinda wonky json back.  it is an array of 

``` ruby
    [{"questions": {...}, {"questions": {...}]
```

In version 0.9.5, it would try to guess the serializer if the each_serializer was nil.  so expected would be:

``` ruby
    { 'questions': [...] }
```

I think what is going on is its using the default `as_json` serializer and instead of the root key having the array, its putting the root on each element in the array.

the adapter I am using is `json`

**Comment by NIHERASE** [comment] 2016-06-08 07:44
+1

**Comment by NullVoxPopuli** [comment] 2016-06-08 11:33
what kind of data is `objects`? (Is it ActiveRecord, is it some custom array?)

**Comment by KevinColemanInc** [comment] 2016-06-09 18:05
@NullVoxPopuli active record models

**Comment by NullVoxPopuli** [comment] 2016-06-15 15:35
do you have a repo that we can checkout and play with this?

**Comment by zts-rbecker** [comment] 2016-08-21 22:56
+1

**Comment by dagumak** [comment] 2018-10-06 01:14
Did anyone figure out how to fix this?

**Comment by bf4** [comment] 2018-10-15 00:29
@dagumak I'm not confident you're commenting on the same version the issue is related to. I'm going to close this. Please open a new issue.  (Generally, when commenting on an open issue with the last comment two years ago, you should make a new issue and reference this.)

**Closed by bf4** 2018-10-15 00:29 UTC

**Comment by KevinColemanInc** [comment] 2018-10-15 04:40
@bf4 

I am pretty sure this is still an issue on the latest version of AMS since no one has linked a pr fixing it.

**Comment by bf4** [comment] 2019-01-21 18:34
@KevinColemanInc I'm happy to facilitate a fix.  As you know, development isn't very active now, in part because I don't think any of the current maintainers are using it.
