### ISSUE TITLE
[0.10.0rc1] `has_many` doesn't work without serializer defined on association

### ISSUE THREAD

**Issue by JustinAiken** [rails-api/active_model_serializers#877] opened 2015-04-22 18:20 UTC
I have this serializer:

```ruby
class BrandSerializer < ActiveModel::Serializer
  attributes ...

  ...
  has_many :style_configurations
...
end
```

`style_configurations` doesn't have an AMS defined, it's just using the standard rails json response.  Under 0.9x this works fine, but on today's new RC, I get this:

```ruby
     NoMethodError:
       undefined method `new' for nil:NilClass
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/array_serializer.rb:17:in `block in initialize'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/array_serializer.rb:12:in `initialize'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:215:in `new'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:215:in `block in each_association'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:208:in `each'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:208:in `each_association'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/adapter/json.rb:17:in `serializable_hash'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/adapter.rb:23:in `as_json'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:34:in `encode'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:21:in `encode'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/action_controller/serialization.rb:49:in `block (2 levels) in <module:Serialization>'
```

**Comment by CV-Gate** [comment] 2015-04-23 17:25
Same here, I avoided specifying a serializer for the relationship.

**Comment by bf4** [comment] 2015-04-25 04:11
Duplicate of https://github.com/rails-api/active_model_serializers/issues/870

**Comment by JustinAiken** [comment] 2015-04-27 22:39
I think it's similar symptoms, but not a dup of #870...

- #870 deals more with when the serializer for the `has_many` does exist, but the options hash for getting the association isn't passing through okay..
- This one is for when the child serializer doesn't exist at all.  In previous versions of AMS, if you have a `Foo` model and a `Bar` model, and the `FooSerializer` `has_many :bars`, but there's no `BarSerializer` at all, it would just stick the standard rails build-in serialization to populate the the `bars` field... now it tosses up that error.

**Comment by joaomdmoura** [comment] 2015-06-12 05:18
I'm also not sure if it's a dup. Not sure if #949 impacts it.
Would be awesome to have a PR with a falling test on this one :smile: @JustinAiken would you be able to do this?

**Comment by bf4** [comment] 2015-06-12 19:11
I think this is related to https://github.com/rails-api/active_model_serializers/issues/945#issuecomment-111329348 as well

**Comment by JustinAiken** [comment] 2015-06-12 21:08
> Would be awesome to have a PR with a falling test on this one :smile: @JustinAiken would you be able to do this?

Done in #955

**Comment by joaomdmoura** [comment] 2015-06-12 22:57
Yeah it's definitely related to #945, I'm interested in make this happen!
@JustinAiken made a great work writing the falling test, I'll try to pick up from there, but I'm kind busy with other couple features now, so in case some of you want to implement it just make yourself comfortable and let me know, otherwise I'll work on it once I finished this new PR, what might be this weekend :smile:

**Closed** 2015-06-26 05:32 UTC
Labels: 0.10.x, Needs Bug Verification
