### ISSUE TITLE
Is it possible to embedd relation with AMS ?

### ISSUE THREAD

**Issue by bsylvain** [rails-api/active_model_serializers#2302] opened 2018-11-26 19:33 UTC
When I have a parent tha has many children in a serializer : 

    has_many :operations,key: 'operations'

Is it possible to, instead of having only a reference, embed the serialized childrens in the same response?

I am using AMS with ember and I am encountering the API version of n+1 query.

Also, if it's possible, how can I make it so that it is enabled or disabled depending of the use case (show vs index) ?

**Comment by bf4** [comment] 2018-11-28 06:39
yes

what have you tried?

what version are you on?

Closing this as it's a variation of 'how do I use AMS', though I'll followup if demonstrate you've done your due diligence.  (Not using the template isn't a good start, fyi)

**Closed by bf4** 2018-11-28 06:39 UTC

**Comment by bsylvain** [comment] 2018-11-28 08:08
I am using AMS 0.10.

Here is how relations in my current payload look like : 

`operations":{"data":[{"id":"5","type":"invoice/operation"}]}`

Here is what I would like to have : 

`operations":{"data":[{"id":"5","attributes":{"state":"payment","payment-type":""}}]}`

My serializer use the following relations : 
```

class InvoicetSerializer < ActiveModel::Serializer
attributes :id,:automatic,:state,:invoice_number,:start,:finish,:total_ttc,
:invoice_date,:payment,:syspay_ref,:order_number

has_many :operations,serializer: OperationSerializer

```
Can AMS embedd a child instead of a link?

I tried to include the relation in the AR query, `:serializer` ans `:each_serializer` options, to add `include=operation` to the query,

**Comment by bf4** [comment] 2018-11-28 21:16
It looks to me like you are using the jsonapi adapter and would the
relationship to reference the full resource object, rather than just the
resource object identifier.  That would violate the jsonapi spec.  The spec
expects you to sideload/embed the relationship using the include query
param and will put all included resource objects in the top level included
member

I'm not sure whether the issue is mostly unfamiliarity with the spec and
difficulty reading the docs or tests or code
