### ISSUE TITLE
using serializer for a hash

### ISSUE THREAD

**Issue by krtschmr** [rails-api/active_model_serializers#2110] opened 2017-04-15 15:36 UTC
we render comments via serializer, including the author and some metadata.

this line is using the serializer and everything works great

    render json: comments

however, we also need to send additional meta-data, so we wrap it into a hash. unfortunately this is not using the serializer and we can't figure out why

    render json: {comments: comments, upvoted: upvoted, downvoted: downvoted}

is this correct behaviour?

**Comment by bf4** [comment] 2017-04-15 20:07
@krtschmr Firstly, thanks for your issue. However, there's a lot of info missing that we asked for in the issue template because it really helps lighten the maintenance burden. Remember, there's a  lot more of 'you' than maintainers.  Lastly, the issue is exactly what you described

> we wrap it into a hash.

AMS looks at the hash and says, 'not my job', and moves on.

duplicate of https://github.com/rails-api/active_model_serializers/issues/2102#issuecomment-293292697

**Closed by bf4** 2017-04-15 20:07 UTC

**Comment by krtschmr** [comment] 2017-04-16 01:37
thank you, @bf4 - working now. 
whats the reason that we don't lookup inside a hash for an ActiveRelation and then serialize it by default? too much magic behavior?

**Comment by bf4** [comment] 2017-04-16 13:33
@krtschmr 

>  too much magic behavior?

pretty much.  can you imagine how it would work? Everything you'd try to render would be to be inspected to see if it was a hash, then inspect every value if has a serializer, is an array, or a hash, etc...  Much easier for the person calling render who know what what to just do the right thing.  Can you imagine all the bugs we'd find?

**Comment by krtschmr** [comment] 2017-04-16 15:23
indeed, if i think about that. if we render 500 keys in a hash, that's 
500 lookups. that's time consuming (expensive) as well.

lets keep it here, keep it classy. thanks for the help



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
