### ISSUE TITLE
Using include_<association>? in 0.10.x not working?

### ISSUE THREAD

**Issue by jensbjork** [rails-api/active_model_serializers#857] opened 2015-03-24 20:29 UTC
In a nutshell, I have the following scenario:

Controller:

    def index
        associations = params[:include] ? params[:include].split(",").map { |v| v.to_sym } : nil
        @posts = @posts.includes(associations)

        if @posts
            render json: @posts, include: params[:include]
        else
            render nothing: true, status: 404
        end
    end

Serializer:

    class PostSerializer < ActiveModel::Serializer
        attributes :id, :title
        has_many :comments

        def include_comments?
            object.association(:comments).loaded?
        end
    end

My goal is to only load and query the database if associations are included in the include get parameter as of the JSON API standard. It seems like the include_association? is not handled at all, I've tried to return false directly in the method, but the assocations still queries the database. E.g:

    def include_comments?
        false
    end

I can't seem find documentation for this. Has the method changed or is there any other preferred way of doing this?

I am using master branch (0.10.x) and the JSON API adapter.

Thanks in advance

**Comment by rowlandrudolf** [comment] 2015-04-30 07:57
Ran into the same situation... If you don't mind having an empty array you can redefine the `:comments` 
```ruby
has_many :comments

def comments
  object.association(:comments).loaded? ? object.comments : [] 
end

```
Or override the `associations` method.. Pretty ugly solution but it works like `include_<assocation>?` 
```ruby
def included_associations
  [ :comments ] #etc..
end

def associations
  object_associations = super
  included_associations.each do |assoc|
    next unless object.association(assoc).loaded?
    object_associations[assoc] = []
    object.public_send(assoc).map { |c| object_associations[assoc] << get_serializer(c).as_json }
  end
  object_associations
end

def get_serializer(object, root=false)
  "#{object.class}Serializer".constantize.new(object, root: root)
end
````

**Comment by scttnlsn** [comment] 2015-05-18 16:01
Is support for `include_<attr or association>?` planned for 0.10.x?

**Comment by ryansch** [comment] 2015-05-18 18:24
I've hit my head on this as well.

**Comment by scttnlsn** [comment] 2015-05-18 18:25
Here's a simple implementation that I'm trying out at the moment: https://github.com/rails-api/active_model_serializers/compare/master...scttnlsn:inclusion

**Comment by joaomdmoura** [comment] 2015-05-18 18:30
I haven't read the thread yet, but it's already in my radar.
@scttnlsn make yourself comfortable,
I can't guarantee that we will merge it, because as I said, I haven't read it yet. But thank you for your help! :+1:

**Comment by lukebergen** [comment] 2015-06-11 13:30
Confirmed that this is also an issue (at least for me) in 0.9.3.

**Comment by joaomdmoura** [comment] 2015-06-12 08:01
ppl, just a quick update, we have being talking about conditional attributes, and we decided that filter will probably be coming back in 0.10.x cc/@lukebergen 

We haven't started it yet because we are busy into some new features to AMS too, but we are willing to review a PR implementing it, otherwise it's already on our todo-list to a near-future. For now I'm closing this PR.

**Closed by joaomdmoura** 2015-06-12 08:01 UTC
Labels: 0.10.x, JSON API, Needs Bug Verification

**Comment by leonelgalan** [comment] 2015-07-02 20:20
Yeah, `include_[attribute]?` was dropped sometime around 0.9.0 ([CHANGELOG.md change](https://github.com/strzalek/active_model_serializers/commit/82a4f25002d4881f20e9c0a8b579eece971b30b6) and [Implentation commit](https://github.com/strzalek/active_model_serializers/commit/841f3b8181e909225a298bbf70f2d09a2f5652dc)) in favor of `filter`. I'm glad to know filter is coming back!

**Comment by dpmccabe** [comment] 2015-07-27 23:39
I wanted to customize both the attributes and the associations according to `some_flag` (where if `true` then only a few of the attributes and one particular association are included) and this is how I solved it:

```ruby
belongs_to :user
belongs_to :bill_address
belongs_to :stripe_card
has_many :shipments

def attributes(options = {})
  if object.some_flag
    super.slice(*%i(number state email errors))
  else
    super
  end
end

def each_association(&block)
  self.class._associations.dup.each do |name, association_options|
    next unless object && included_associations.include?(name)

    association_value = send(name)

    serializer_class = ActiveModel::Serializer.serializer_for(association_value, association_options)

    serializer = serializer_class.new(
      association_value,
      options.merge(serializer_from_options(association_options))
    ) if serializer_class

    if block_given?
      block.call(name, serializer, association_options[:association_options])
    end
  end
end

def included_associations
  if object.some_flag
    %i(bill_address)
  else
    %i(user bill_address stripe_card shipments)
  end
end
```

**Comment by joaomdmoura** [comment] 2015-07-31 14:17
@dpmccabe would be awesome if you could checkout https://github.com/rails-api/active_model_serializers/pull/999 and give it try. Check if it solves your problema, if it does :+1: it. :smile:

**Comment by sars** [comment] 2016-03-01 01:47
Guys, any updates on this issue?

**Comment by bf4** [comment] 2016-03-01 09:00
@sars Are you asking about conditional attributes? If so, they're implemented in master. If you're asking about the specific syntax, it is not planned at present to re-introduce it, except, perhaps, in a 'legacy' serializer.
