### ISSUE TITLE
Question: Programmatically invoking ArraySerializer for JSONAPI

### ISSUE THREAD

**Issue by shicholas** [rails-api/active_model_serializers#1002] opened 2015-07-13 16:27 UTC
I am trying to write a controller spec for something that already works as expected, namely:

```ruby
  render json: products, include: 'category', meta: pagination
```

which gives me the JSON API that I expect. I'm trying to write something like this in my tests:

```ruby
product = FactoryGirl.create(:product)
expected_json = ActiveModel::Serializer::Adapter.create(
  ActiveModel::Serializer::ArraySerializer.new(
    [product], 
    included: 'category'
    meta: pagination
  )
).to_json
```

but I can't seem to get the ``included`` part to display (the ``data`` and ``meta`` attributes work just fine). Any help to programatically create a JSON document w/ ``included`` would be greatly appreciated.

**Comment by bf4** [comment] 2015-07-14 02:04
what version are you one? Which ruby? Ruby version? Rails version?

Right now, in order to get what you want, you need to crib the code from the controller.  There's some examples in https://github.com/rails-api/active_model_serializers/pull/889#issuecomment-109348755

Soon, when #954 is merged, you'll be able to just use that.

**Comment by shicholas** [comment] 2015-07-14 02:10
thanks for the quick response @bf4!

> what version are you one? Which ruby? Ruby version? Rails version?
0.10.0.rc2, 2.2.2p95, 4.2.3

I'll try the comment you referenced and get back shortly. Thanks again!

**Comment by shicholas** [comment] 2015-07-14 03:19
unfortunately I got:

>     Failure/Error: adapter = ActiveModel::Serializer::Adapter.create(serializer_instance, adapter_opts)
>     NoMethodError:
>       undefined method `new' for nil:NilClass

with both the rc2 and the latest master. Here is my code:

```ruby
serializer = ActiveModel::Serializer.serializer_for(product)
serializer_opts = {
  each_serializer: serializer,
  included: %w(
    category
  ),
  meta: pagination
}
serializer_instance = serializer.new(product, serializer_opts)
adapter_opts = {adapter: "jsonapi"}

adapter = ActiveModel::Serializer::Adapter.create(serializer_instance, adapter_opts)
adapter.as_json
```

I will dig deeper into this over the weekend.

**Comment by bf4** [comment] 2015-07-14 06:11
I think the problem is that the adapter is `json_api` not `jsonapi`.

If that doesn't work, you can also try setting Serializer.adapter = ActiveModel::Serializer::JsonApi

what are `serializer` and `product` in the above?

**Comment by bf4** [comment] 2015-07-14 06:13
Also, for reasons, in the controller `each_serializer: serializer` becomes `serializer: serializer`, which is used by ArraySerializer (if you have a collection, which product doesn't appear to be)

**Comment by shicholas** [comment] 2015-07-14 06:20
thanks! ``json_api`` resolved the nil issue. I am still having trouble getting the ``included`` working with this code (meta and data work as expected):

```ruby
serializer = ActiveModel::Serializer.serializer_for([product])
serializer_opts = {
  each_serializer: serializer,
  included: %w(
    category
  ),
  meta: pagination
}
serializer_instance = serializer.new([product], serializer_opts)
adapter_opts = {adapter: "json_api"}

adapter = ActiveModel::Serializer::Adapter.create(serializer_instance, adapter_opts)
adapter.as_json
```

**Comment by bf4** [comment] 2015-07-14 06:21
[see which opts go the serializer and which to the adapter](https://github.com/rails-api/active_model_serializers/blob/954e4c51fe6ff4ebbca1692045b3decf3cc1633d/lib/action_controller/serialization.rb#L9)

include (not included) is an adapter opt

**Comment by shicholas** [comment] 2015-07-14 06:25
thanks for your help, this worked!

```ruby
serializer = ActiveModel::Serializer.serializer_for([product])
serializer_opts = {
  each_serializer: serializer,
  meta: pagination
}
serializer_instance = serializer.new([product], serializer_opts)
adapter_opts = {adapter: "json_api", include: ['category']}

adapter = ActiveModel::Serializer::Adapter.create(serializer_instance, adapter_opts)
adapter.as_json
```

**Closed** 2015-07-14 06:27 UTC

**Comment by bf4** [comment] 2015-07-14 06:28
@joaomdmoura wanna mark this for documentation?

**Comment by joaomdmoura** [comment] 2015-07-21 03:08
Hey ppl, have just read trough it, I'm glad you figured that out!
Of course, I'm always up for documentation! I'll check the #1005 before open a new issue.

**Comment by Zelnox** [comment] 2015-07-22 13:00
This was helpful. In terms of performance compared to 0.8.x, it's a bit slower due to the adapter step.
