### ISSUE TITLE
has_many uses the wrong serializer

### ISSUE THREAD

**Issue by bufordtaylor** [rails-api/active_model_serializers#1342] opened 2015-11-24 06:45 UTC
Banging my head trying to figure out what is going on here. on 0.10.0.rc3

```ruby
   class Project < ActiveRecord::Base
      has_many :roles
   end

   class Role < ActiveRecord::Base
      has_many :auditions
   end

   class Audition < ActiveRecord::Base
   end

   class ProjectSerializer < ActiveModel::Serializer
      attributes :id
      has_many :roles
   end

   class RoleSerializer < ActiveModel::Serializer
      attributes :id
      has_many :auditions
   end

   class AuditionSerializer < ActiveModel::Serializer
      attributes :id
   end

```

output using no config adapter

```
{
  id: 6806,
  roles: [
    {
      id: 49371
    }
}
```

output using json adapter

```
{
  project: {
    id: 6806,
    roles: [
      {
        id: 49371
      }
}
```

output using json_api adapter

```
data: {
  id: "6806",
  type: "projects",
  relationships: {
    roles: {
      data: [
        {
           id: "49371",
           type: "roles"
        }
   included: [
     {
        id: "49371",
        type: "roles",
        relationships: {
           auditions: {
             data: [
               {
                 id: "57617",
                 type: "auditions"
               }
etc...
```
For sanity, Role.find(49371) has records of auditions in the database. Why do the audition records only appear on the json_api adapter?

I tried a few things to try to get it to work on the non json_api adapters, like

```has_many :auditions, serializer: AuditionSerializer```

Same result.

Even tried this

```ruby
   class RoleSerializer < ActiveModel::Serializer
      attributes :id, :auditions
      def auditions
          object.auditions.each do |aud|
              AuditionSerializer.new(aud)
          end
      end
   end
```
This *did* get auditions to show on non json_api adapters, but it *did not* use the AuditionSerializer, as it contained `created_at` and other attributes I did not set.

The crazy thing is that is **IS** calling AuditionSerializer, as I overrode the `initialize` method to check if it's being called, but it's still outputting the wrong attributes.

More crazy things:

`ap ActiveModel::SerializableResource.new(Role.find(49371)).serializable_hash` yields results **with** auditions
`ap ActiveModel::SerializableResource.new(Project.find(6806)).serializable_hash` yields results **without** auditions regardless of the adapter

Just tried in 0.9.0. Worked fine.

**Comment by bufordtaylor** [comment] 2015-11-24 08:24
FYI, I was able to get this working using this code:

```ruby
class RoleSerializer < ActiveModel::Serializer
  attributes :id, :auditions

  def auditions
    object.auditions.map do |aud|
      ActiveModel::SerializableResource.new(aud, {})
    end
  end
```

**Comment by bf4** [comment] 2015-11-24 17:39
Does your `render` specify any serializer options?  Have you tried removing those?

**Comment by bufordtaylor** [comment] 2015-11-24 17:42
I'm just calling the plain `json: @project` in the controller.

In the console, I don't set any options either:

`ap ActiveModel::SerializableResource.new(Role.find(49371)).serializable_hash` yields results with auditions
`ap ActiveModel::SerializableResource.new(Project.find(6806)).serializable_hash` yields results without auditions regardless of the adapter

**Comment by bf4** [comment] 2015-11-24 19:33
Oh, I think this is because AMS won't included the third level resource by default.  I believe, @beauby can correct me, you can include an infinite depth of resources using `include: '*'`.

**Comment by beauby** [comment] 2015-11-24 19:54
@bf4 Actually, `include: '*'` includes only one level. You can do `include: '*.*.*.*'` to include 4 levels, or `include: '**'` to include an infinite depth of resources.

**Comment by bf4** [comment] 2015-11-24 20:19
@beauby or `include: 'project.role.audition'` would be more correct?

**Comment by beauby** [comment] 2015-11-24 21:28
@bf4 more correct than what?

**Comment by tumayun** [comment] 2015-11-26 09:22
I have the same problem.
What do I do?

**Comment by bufordtaylor** [comment] 2015-11-26 19:16
I was unable to make it work with the above suggestions, @tumayun. For now, I'm going with 0.9.0 until I can debug further.

**Comment by bf4** [comment] 2015-11-27 02:38
We can help if you share some failing code we can reproduce.  The behavior should be pretty straight forward 

B mobile phone

**Comment by beauby** [comment] 2015-11-27 10:38
@bufordtaylor `render json: @posts, include: '**'` should do what you're trying to achieve.

**Comment by luizbafilho** [comment] 2015-12-03 16:15
Thanks @beauby the ```include``` option worked for me. There is global way to set that as a default ? I don't want to include that option to every ```render``` in my app.

**Comment by bf4** [comment] 2015-12-03 21:50
I asked: 

> @beauby or include: 'project.role.audition' would be more correct?

@beauby asked:

> @bf4 more correct than what?

So, there's two uses of `include`, I'm suggesting

- JSON API-approach: where you want the request to include some specific data, in addition to the primary data
- Nesting approach: where, for whatever reason, you want to include multiple layers of nested associations.

So, if you want to include `project.role.audition`, that should be the argument.  If you want to include everything, then `**` should be the argument.  Otherwise, `**` is just being lazy and asking for trouble, right?  There's a reason more than two layers of nesting is discouraged., no?

**Comment by bf4** [comment] 2015-12-03 21:51
@bufordtaylor If you pick 0.9, you'll help us write upgrade to 0.10 docs? :smile: (I think we generally would recommend 0.8 over 0.9 at this point, but it's been awhile for me.)

**Comment by beauby** [comment] 2015-12-08 17:58
@luizbafilho Currently, there is no option to globally set the default nesting to be unbounded (or anything different than one level, really). I opened an issue to discuss whether we should change the default, but it didn't get much traction.
@bf4 To be fair, the reason more than one level of nesting is discouraged is not that clear to me

**Comment by bf4** [comment] 2015-12-09 04:17
@beauby 

> To be fair, the reason more than one level of nesting is discouraged is not that clear to me

I think there's probably a whole bunch of reasons that can be boiled down to people with a lot of experience designing resource-oriented endpoints have found it easier to work with and less bug-prone.  I think we'd agree 5 levels is too much? So there's a limit somewhere.

Also, it introduces possible recursion issues in the code and can create duplicate resources. I've come across this but can't think of a good example, something like e.g an Author has many blog posts that each have many commenters which each have an author which etc.

That said, graph apis like Facebook and whatever you call the think Netflix does might make more sense, but that's not what we're doing :)

**Comment by beauby** [comment] 2015-12-09 12:11
@bf4: Agreed that for the "legacy" Attributes/Json adapters, it can lead to possible infinite recursions and almost certain duplications. But those are actually design flaws in the structuring of data, not in the serialization process. However, I'm personally fine with it, I just wanted the reasons to be stated for the record.

**Comment by bf4** [comment] 2015-12-09 15:00
I wouldn't say that's **the** reason. We inherited it, and this lib's history is bound to that of JSON API which, after much discussion etc.there's probably a nice issue there somewhere where they discuss (bikeshed) nesting

B mobile phone

**Comment by beauby** [comment] 2016-01-20 00:32
Closing this as it seems to be solved. Feel free to reopen/keep commenting if needed.

**Closed by beauby** 2016-01-20 00:32 UTC
Labels: Needs Submitter Response, Question, V: 0.10.x
