### ISSUE TITLE
embed :ids not functioning as expected

### ISSUE THREAD

**Issue by joshpfosi** [rails-api/active_model_serializers#784] opened 2015-01-19 21:25 UTC
UPDATE: Switched back to AMS version 0.8.3 and am manually adding `embed: :ids, embed_in_root: true` which is working. Not sure why this was not.

I have a rails backend to an ember-data (1.0.0-beta.12) w/ ember-cli front end. I'm using active_model_serializer 0.9.2, with an initializer `config/initializers/active_model.rb`:

```
ActiveModel::Serializer.setup do |config|
  config.embed = :ids
  config.embed_in_root = true
end
```

and a (simplified) serializer:

```
class SchoolSerializer < ActiveModel::Serializer
  attributes :id, :name, :info

  has_many :mentors
end
```

When my front end requests `/schools`, the response isn't correctly embedded, i.e.

```
[  
   {  
      "id":1,
      "name":"Phillips Academy Andover",
      "info":"Consequatur ab quia maxime a voluptas. Saepe quidem provident facere voluptates sint beatae. Eos sed deleniti aspernatur eaque ipsum aut nulla. Molestias cum in enim consequatur et soluta.",
      "created_at":"2015-01-19T02:41:02.339Z",
      "updated_at":"2015-01-19T02:41:02.339Z"
   }
]
```

Not sure what's causing this. It isn't resolved if I put embed :ids at the top of the serializer itself either.

**Comment by antstorm** [comment] 2015-01-20 21:49
From what I see the `SchoolSerializer` is not even used to render JSON, because there are `created_at` and `updated_at` fields in the response, that are not mentioned in your serializer.

Can you show how you render the response? Try passing your `render :json` call a `serializer: SchoolSerializer` option to force the use of it.

**Comment by prasadsurase** [comment] 2015-04-08 06:50
Could not reproduce the error using ruby 2.1.5, rails 4.2.0, active_model_serializers 0.9.2

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
   source 'https://rubygems.org'

   ruby '2.1.5'

   gem 'rails' , '4.2.0'
   gem 'arel'
   gem 'sqlite3'
   gem 'active_model_serializers', '0.9.2'
   gem 'pry'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'active_model_serializers'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.string :title
    t.text :body
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
    t.string :name
    t.text :body
  end
end

class Post < ActiveRecord::Base
  validates :title, :body, presence: true
  has_many :comments
end

class Comment < ActiveRecord::Base
  validates :name, :body, :post_id, presence: true
  belongs_to :post
end

ActiveModel::Serializer.setup do |config|
  config.embed = :ids
  config.embed_in_root = true
end

class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body
  has_many :comments#, embeds: :ids, embed_in_root: true
end

class CommentSerializer < ActiveModel::Serializer
  attributes :id, :name, :body
end

class BugTest < Minitest::Test
  def test_filter_method
    post = Post.create!(title: 'Test filter', body: 'Test if the filter method is working fine')
    comment_1 = Comment.create!(name: 'Prasad', body: 'checking...', post: post)
    comment_2 = Comment.create!(name: 'Prasad', body: 'checked. works fine.', post: post)
    assert_equal CommentSerializer.new(comment_1).to_json, {comment: {id: comment_1.id, name: comment_1.name, body: comment_1.body}}.to_json
    assert_equal PostSerializer.new(post).to_json, {post: {id: post.id, title: post.title, body: post.body, comment_ids: [comment_1.id, comment_2.id]}, comments: [{id: comment_1.id, name: comment_1.name, body: comment_1.body}, {id: comment_2.id, name: comment_2.name, body: comment_2.body}]}.to_json
  end
end
```

**Comment by joaomdmoura** [comment] 2015-06-12 07:49
Taking into account that we were unable to reproduce it and we would need the controller code to move forward into debugging this, I'm closing it for now.

**Closed by joaomdmoura** 2015-06-12 07:49 UTC
Labels: 0.9.x

**Comment by evolve2k** [comment] 2016-08-15 05:24
Although not directly relevant I came here as I was getting the error "undefined method `setup' for ActiveModel::Serializer:Class (NoMethodError)". As it seems ActiveModel::Serializer.setup is no longer supported from version 10.  I was just trying to namespace my json. 

To help anyone else who comes after me. 

You can remove this:

```
# config/initializers/active_model.rb
ActiveModel::Serializer.setup do |config|
  config.embed = :ids
  config.embed_in_root = true
end
```

and replace it with this.

```
# config/initializers/active_model.rb
ActiveRecord::Base.include_root_in_json = true
```

Reference: http://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html
