### ISSUE TITLE
json serializer ignores nested associations

### ISSUE THREAD

**Issue by quaternion** [rails-api/active_model_serializers#921] opened 2015-05-21 10:56 UTC
Example 0.10.x:
````ruby
class NodeSerializer < ActiveModel::Serializer
  attribute :id
end

class UserSerializer < ActiveModel::Serializer
  attribute :id
  attribute :name
  belongs_to :node # <--- ignored
end

class PostSerializer < ActiveModel::Serializer
  attribute :id
  belongs_to :user
end
````
PostSerializer produces json without a user node:
````
{ id: 1, user: { id: 1, name: 'Bob' } }
````
Is this a bug or a feature?

**Comment by groyoh** [comment] 2015-05-21 14:54
If you're using the JSON adapter then it is the expected behavior. The JSON adapter only render the attributes of associations (see [here](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json.rb#L28))

**Comment by quaternion** [comment] 2015-05-21 16:55
Yes, you are right. I use json adapter.

**Comment by groyoh** [comment] 2015-05-21 17:50
If you need a workaround, you can do this:
```ruby
class UserSerializer < ActiveModel::Serializer
  attribute :id
  attribute :name
  attribute :node
  def node
    serializer = ActiveModel::Serializer.serializer_for(object.node).new(object.node)
    ActiveModel::Serializer::Adapter::Json.new(serializer).as_json
  end
end
```

**Comment by chrisbranson** [comment] 2015-05-27 17:47
I ran into this today, having previously used 0.9.x where nested associations were found. Is this 'expected behaviour' in that that's the way it is supposed to work, or would a PR be welcome? A small change gets this behaviour back - see my fork https://github.com/insphire/active_model_serializers/commit/80de7191ef6e79c79714ef1a011c46c22ddff210

**Comment by joaomdmoura** [comment] 2015-05-29 07:21
@quaternion ans @groyoh said, this is indeed the expected behaviour.
This approach takes into account a more lean implementation avoiding heavy responses and also trying to help people into build a "more RESTfull" API.
I'm no saying we will definitely keep it this way, but before move forward into a PR I would like to hear more opinions from other AMS members. cc @kurko @guilleiguaran 
I'm closing this for now. But lets keep the discussion :smile:

**Closed by joaomdmoura** 2015-05-29 07:21 UTC

**Comment by aaronlerch** [comment] 2015-06-03 20:45
This one caught me doing an upgrade from 0.9 -> 0.10. The frustrating part is that I couldn't find any documentation about it, though perhaps I wasn't searching for the right terms. So I ended up spending a bit of time debugging why it was silently ignoring my `has_many` relationships. What really threw me off was that it worked for the top-level `has_many`, so it seemed more like a bug or a configuration issue than an "as intended" behavior.

I get the mindset behind guiding people towards a more lean implementation, however it seems that guidance would be better put into documentation and "how to" write-ups instead of a behavior change resulting in inconsistency. It seems like, unless you just plain don't want to support nested associations for "opinionated framework" reasons, offer the API and simply _guide_ people away from using it.

As for my opinion, I think it should be supported to use `has_many` in nested serializers. Not every use-case is best served by fully "lean-ing" up the API. There are considerations to make, such as mobile-first scenarios in lower bandwidth areas. In this scenario (and where the app supports caching the information for offline access) it can be preferable to send a larger payload once instead of many smaller payloads. In the case of the app I'm working on, that's a tradeoff we have made in the API to better support the use-cases.

Hope that helps add a data point to your decision-making process. Thanks!

**Comment by chibicode** [comment] 2015-08-22 09:39
Waiting for this PR: https://github.com/rails-api/active_model_serializers/pull/952 and  relevant issue: https://github.com/rails-api/active_model_serializers/issues/835#issuecomment-12919875)

By the way, to add to @groyoh's comment (https://github.com/rails-api/active_model_serializers/issues/921#issuecomment-104370171), for `has_many` relationships, you can try something like this:

```ruby
class Post
  attributes :comments
  
  def comments
    object
      .comments
      .map { |x| ActiveModel::Serializer::Adapter::FlattenJson.new(CommentSerializer.new(x)).as_json }
  end
end
```

**Comment by joaomdmoura** [comment] 2015-08-22 17:31
Hey everyone there is actually a new PR in place as well, it's a different approach I have not review it yet, but it _seems_ nice: https://github.com/rails-api/active_model_serializers/pull/1073
