### ISSUE TITLE
Doesn't work on Rails 4.2.0 beta

### ISSUE THREAD

**Issue by bigardone** [rails-api/active_model_serializers#641] opened 2014-09-06 13:18 UTC
Hi!
I've been playing around with **Rails 4.2.0beta** and **active_model_serializers**, but it doesn't work. When rendering json in a controller it doesn't use the generated serializer.
This is the serializer:
https://github.com/bigardone/rails_and_react/blob/master/app/serializers/person_serializer.rb
And this the controller:
https://github.com/bigardone/rails_and_react/blob/master/app/controllers/people_controller.rb

Am I doing anything wrong or missing anything?

Thanks in advance!

**Comment by barberj** [comment] 2015-01-04 23:40
@igagnidz's fix didn't work for me. I'm on rails (4.2.0) non beta. I have ended up just using jbuilder which ships with rails now.

**Comment by dbackeus** [comment] 2015-01-05 11:43
+1

We are using active_model_serializers with mongoid together with respond_with (now responders gem) and didn't work out of the box after the rails 4.2 upgrade. Explicitly initialising our serializers seems ok as a work around for now.

**Comment by kapso** [comment] 2015-01-12 09:21
Running into similar issues with Rails 4.2. Is there a release date for `0-9-stable`.

Thanks much!

**Comment by iRonin** [comment] 2015-01-12 11:14
thx @igagnidz! :+1:

**Comment by bf4** [comment] 2015-01-13 02:24
Taking @igagnidz comment, applied as follows

```ruby
# Gemfile
gem "active_model_serializers", "~> 0.9.2"

# config/initializers/0_extensions.rb
Dir[Rails.root.join("lib/extensions/*.rb")].each do |file|
  require file
end

# lib/extensions/active_model_serializers.rb
gem "active_model_serializers", "= 0.9.2"
# blow up when this patch it no longer needed
# see https://github.com/rails-api/active_model_serializers/issues/641#issuecomment-68196151
require "active_model_serializers"
module RailsApiSerializationPatch
  def _render_with_renderer_json(json, options)
    serializer = build_json_serializer(json, options)

    if serializer
      super(serializer, options)
    else
      super(json, options)
    end
  end
end
ActiveSupport.on_load(:action_controller) do
  include RailsApiSerializationPatch
end
```

**Comment by MarshalGeazipp** [comment] 2015-01-13 21:20
thx @igagnidz and @bf4 ! :+1:

**Comment by dirkkelly** [comment] 2015-01-14 07:16
:+1: @igagnidz and @bf4

**Comment by ankit8898** [comment] 2015-01-20 19:43
Patch works thanks @igagnidz and @bf4 :+1:

**Comment by sb8244** [comment] 2015-01-21 04:17
Confirmed patch works for me

**Comment by yagooar** [comment] 2015-01-21 09:35
I must say, I'm pretty scared seeing how easily people would take and patch internal APIs. This is just a ticking timebomb, until the next dev updates the gem or another dependency and it all blows up. Guys, software engineering is more than just blindly copying&pasting of monkey patches, please make sure to understand what the underlying code changes.

**Comment by iRonin** [comment] 2015-01-21 12:01
@yagooar Aren't you scared to use any gem at all? :)
Pretty scary when you start to think what's inside ;)

**Comment by yagooar** [comment] 2015-01-21 12:06
@iRonin It's not the same thing using gems and monkey patching private APIs. But yes, sometimes I am scared when I see what an overdose of gems can do to a project. Thus I always try to use battle-tested gems, with a good reputation and even better, I try to take at least a brief look at the source code.

It's just that once you have seen a project collapse because of monkey patching and gem overuse, you start looking suspicously at every new gem you (or the developers in your team) introduce to the application.

What I'm trying to say is that you should always check what kind of code you are introducing into your applications, and avoid monkey patching if there is another way. In the long run, your application will be more solid and you'll sleep better, I talk from experience ;)

**Comment by dbackeus** [comment] 2015-01-21 13:04
@yagooar Though I see where you concerns are coming from. There are more or less scary approaches to using patches.

If it's something you can use as a hotfix for a bug until a proper branch or fixed release is available it might be your best option. In our case the monkey patch didn't even work. But if it had, our workflow had probably been:

1. Apply the monkey patch in config/initializers/patches.rb (fairly common convention to use such a file) and make sure all specs pass
2. Remove the monkey patch and switch the Gemfile to the fixed branch (https://github.com/rails-api/active_model_serializers/pull/776) as soon as that was available (which we found out through watching this thread) and make sure all specs pass + give feedback in the PR that it's working
3. When the PR is merged into master and a new active_model_serializers release has been made, remove the referenced fork from the gemfile, bundle update and make sure all specs pass

I would think of a new release of the gem as the reverse of a ticking timebomb - that's the moment we disarm the bomb and breathe a sigh of relief :)

**Comment by sb8244** [comment] 2015-01-21 13:25
Yea personally, I'm using this on a side project that I wanted to try the
new Rails and ruby versions on. Throw patch in an initialization with the
intent to throw away.

It's clearly a bug that I don't intend on wasting anymore of my time on in
my project, unless ams wants help fixing the problem  (I bet they have it
under control). However it should probably be fixed soon to not drive
people away from the gem


-- 


  Steve Bussey •SalesLoft

•Software Engineer

e steve.bussey@salesloft.com w salesloft.com
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

a 3423 Piedmont Rd NE, Atlanta, GA 30305

[image: Facebook] <https://www.facebook.com/SalesLoft> [image: Twitter]
<https://twitter.com/SalesLoft> [image: Linkedin]
<https://www.linkedin.com/company/salesloft> [image: wordpress]
<http://blog.salesloft.com/blog/> [image:
http://salesloft.com/prospector/#video]
<http://salesloft.com/prospector/#video>  [image: Software Engineer Logo]
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

**Comment by bf4** [comment] 2015-01-21 14:55
>
A good patch should

1) self-destruct when the version changes

2) document why it's there and when it can be removed in a comment

This does both.

That said, it seems to me this lib and rails-api are slowly dying due
to decreased maintenance.  I offer myself to help.
>

**Comment by steveklabnik** [comment] 2015-01-21 15:39
> decreased maintenance

We actually just got sponsorship from Ride, and @kurko has work-time to
work on it. So that's technically better maintenance than we've ever had
:wink:

**Comment by iRonin** [comment] 2015-01-21 15:41
Nice! :+1:

**Comment by subicura** [comment] 2015-01-21 16:41
good :+1:

**Comment by kurko** [comment] 2015-01-21 20:46
Released https://rubygems.org/gems/active_model_serializers/versions/0.9.3. It's basically 0.9.1 (tons of bugfixes) minus the commit that caused tons of regressions. Please test and let us know how it goes :grin:

**Comment by ankit8898** [comment] 2015-01-21 20:56
@kurko Works as expected. Using Rails 4.2, active_model_serializers 0.9.3 :+1:  
Thank you!

**Comment by kurko** [comment] 2015-01-21 20:57
<3

**Closed by kurko** 2015-01-21 20:57 UTC
Labels: 0.9.x, bug

**Comment by steveklabnik** [comment] 2015-01-21 21:20
:confetti_ball:

**Comment by meskyanichi** [comment] 2015-01-21 21:44
Confirmed to be working here as well! :+1:

**Comment by sb8244** [comment] 2015-01-21 21:45
:+1:

**Comment by bf4** [comment] 2015-01-21 22:31
@steveklabnik @kurko Thanks for all your work!

**Comment by kapso** [comment] 2015-01-22 05:28
Draper breaks after upgrading to `active_model_serializers 0.9.3` - https://github.com/drapergem/draper/issues/651

**Comment by sdn90** [comment] 2015-01-26 01:38
Can't get it to work using Rails 4.2.0 and have tried AMS 0.8.3, 0.9.2, and 0.9.3.

**Comment by kurko** [comment] 2015-01-26 01:43
@sdn90 can you:

1. open a new issue
2. detail the errors you're seeing with ways to reproduce this?

**Comment by sebastianvera** [comment] 2015-02-19 22:05
:+1: @sdn90

**Comment by bf4** [comment] 2015-02-25 22:06
@kurko maybe lock this thread?

**Comment by vmanamino** [comment] 2015-08-30 06:39
@igagnidz Your patch worked perfectly for me.

**Comment by joaomdmoura** [comment] 2015-09-07 15:03
Nice @vmanamino, I'd recommend you also to give it a try to 0.10.x :grin:  elt us know in case you need some help when migrating

**Comment by kulbida** [comment] 2016-04-27 02:24
I'm having the same issue with AMS 0.9.5 and Rails 4.2.5.

**Comment by bf4** [comment] 2016-04-27 03:34
This is resolved. Please open a new issue , link here, and answer the issue
questions
