### ISSUE TITLE
Manual serialization for embedding in a attribute

### ISSUE THREAD

**Issue by brauliobo** [rails-api/active_model_serializers#1204] opened 2015-09-27 12:58 UTC
I need to serialize manually, either to test on the console but mainly for a riot component, something like

```slim
= riot_component :my_tag, data: XSerializer.new(@obj).attributes.to_json
```

But `attributes` does not includes associations. So, how to do it?

**Comment by NullVoxPopuli** [comment] 2015-09-27 15:28
Have you tried `SerializableResource.new(obj).serializable_hash`?

**Comment by beauby** [comment] 2015-09-27 17:18
@brauliobo As @NullVoxPopuli said, and as mentioned in the [docs](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md), in order to use AMS outside of a Rails controller, you just have to 
```ruby
ActiveModel::SerializableResource.new(@obj).serializable_hash.to_json
```
If you find the docs are not clear, we'd love for you to provide a PR making it better.

Closing this for now, feel free to reopen if you need further assistance.

**Closed by beauby** 2015-09-27 17:18 UTC

**Comment by brauliobo** [comment] 2015-09-27 22:06
@beauby @NullVoxPopuli ok, this seems rather long to me. You think it would be good to have a `seriarialize_hash` method on `ActiveModel::Serializer` that just do this?
Something like:
```ruby
class ActiveModel::Serializer

  def serializable_hash
    ActiveModel::SerializableResource.new(self.object).serializable_hash
  end 

end
```

**Comment by brauliobo** [comment] 2015-09-27 22:19
Also, `serializable_hash` is rather long and difficult to type, maybe `to_hash` or something else as an alias to it...

**Comment by beauby** [comment] 2015-09-27 22:20
I agree with you to some extent that the naming is not optimal. Thoughts @bf4, @joaomdmoura, @NullVoxPopuli?

**Comment by brauliobo** [comment] 2015-09-27 22:31
@beauby now maybe a bug. When I serialize `ContextSerializer`, which has many `TeamSerializer`, which has many `MemberSerializer`, the has_many `MemberSerializer` is discarded. Is it not recursive?

**Comment by beauby** [comment] 2015-09-27 22:55
@brauliobo Could you open a separate issue for this, with your serializers and specifying the adapter used?

**Comment by brauliobo** [comment] 2015-09-27 23:03
@beauby done, #1205

**Comment by brauliobo** [comment] 2015-09-27 23:10
Addressing #1205 at the same time, would do:
```ruby
class ActiveModel::Serializer

  def serializable_hash
    ActiveModel::SerializableResource.new(self.object, serializer: self.class, include: '**').serializable_hash
  end 

end
```

**Comment by beauby** [comment] 2015-09-27 23:15
@brauliobo It being technically feasible is not the issue here. The issue is mainly separation of concerns between classes, and so far it has been deemed outside of the serializer's scope to actually build a serializable hash for a resource (the rationale behind it being that a serializer should only be concerned with presenting one type of resources, not its associations). 
Feel free to open an issue for discussing possible alternatives for this architecture. I think it's important we discuss that with the users.

**Comment by brauliobo** [comment] 2015-09-27 23:19
@beauby ok, will keep that in mind. This is my first week on AMS, and it only maked sense to serialize using the serializer itself, this concept of SerializableResource is still not yet fully justified to me, as the serializer is already linked to the resource (`object`).

**Comment by beauby** [comment] 2015-09-27 23:25
I totally understand that, and I've been working on some doc that explain the internal of AMS so that new contributors can grasp it more quickly. Roughly:
 + **serializers** present models for serialization (that is, they describe *what* will be serialized, and under *what name*),
 + **adapters** take a bunch of serializer instances and build a hash that's ready for JSONification (the structure of the hash depends on the adapter),
 + `SerializableResource` takes a resource and builds the corresponding serializer instances for it and its associations, and passes it to the adapter. (@bf4, tell me if I'm wrong)

**Comment by brauliobo** [comment] 2015-09-27 23:38
Yeah, the concept of serializers and adapters are quite easy to understand and accept. For adapters I would only add some configuration (for example, customize root key on `:json`)

**Comment by beauby** [comment] 2015-09-27 23:40
@brauliobo This is already the case. If you'd like to further discuss AMS-related stuff, feel free to join us on the [AMS slack](http://amserializers.slack.com).

**Comment by NullVoxPopuli** [comment] 2015-09-28 02:08
as for the naming of `serializable_hash`, I think `to_hash` would be generic enough to make sense, but not too generic to not may sense, if that makes any sense :-) 

We are technically converted models/associations to a hash, and while it doesn't exactly say what is going on, I think that's what may be implied by passing the model to `SerializableResource.new`

**Comment by bf4** [comment] 2015-09-28 02:22
No!!!!!! It's the ActiveModel::Serialization interface.  Take it up with Rails

Also, it's not a problem except for lib authors

B mobile phone

**Comment by bf4** [comment] 2015-09-28 02:23
Please read the Lint

B mobile phone
