### ISSUE TITLE
Example for local adapter setting?

### ISSUE THREAD

**Issue by PaulOstazeski** [rails-api/active_model_serializers#1945] opened 2016-10-14 18:23 UTC
#### Expected behavior vs actual behavior
The docs at https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md seem to indicate that it is possible to define a global adapter **and** override that for individual serializers. That is, if I want `:json_api` to be used for serializing `Foo` and `Bar`, but I want plain old `:json` for serializing `Baz`.

Is that possible? Can anyone share an example to help me in the right direction?

#### Steps to reproduce
If I set
```ruby
ActiveModelSerializers.config.adapter = :json_api
```

 in an initializer, and then I have

```ruby
class BazSerializer < ActiveModel::Serializer
    config.adapter = :json
end
```

and
```ruby
render json: Baz.first
```

in a controller, then I see requests to that action are using json-api formatting and not json.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
0.10.2

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

OS Type & Version: 
Linux

Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails v5.0.1

**Comment by AlexWheeler** [comment] 2016-10-20 21:33
@PaulOstazeski Reading the docs at https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md under _SerializableResource options_ it looks like you can override the configured adapter when rendering with the following:
i.e. if you have

`ActiveModelSerializers.config.adapter = :json_api`, but want to render BazSerializer with :json adapter then you could do:

`render json: Baz.first, adapter: :json`

But it doesn't look like you can override _within_ a serializer.  Does that help?

**Comment by beauby** [comment] 2016-10-21 01:03
Serializers have no knowledge of the adapter. This is by design. Closing this issue but feel free to keep commenting if you need help.

**Closed by beauby** 2016-10-21 01:03 UTC
