### ISSUE TITLE
JSON-API includes

### ISSUE THREAD

**Issue by xn** [rails-api/active_model_serializers#1164] opened 2015-09-16 23:11 UTC
How do I configure or where does the logic live to select which serializer serializes an include in the json-api adapter?

I've got a situation like:

```
module Blah
  module V1
    module Serializers
      class FooSerializer < AMS
        attribute: id
        has_many :bars, serializer: Blah::V1::Serializers::BarSerializer
      end
    end
  end
end
```
What I want is:
```
{
  "data": {
    "id": "1",
    "type": "foos",
    "attributes": {
    },
    "relationships": {
      "bars": {
        "data": [
          {
            "id": "1",
            "type": "bars"
          }
        ]
      }
    }
  },
  "included": [
    {
      "id": "1",
      "type": "bars",
      "attributes": {
      }
    }
  ]
}
```
What I get is (note the integer ID in the includes):

```
{
  "data": {
    "id": "1",
    "type": "foos",
    "attributes": {
    },
    "relationships": {
      "bars": {
        "data": [
          {
            "id": "1",
            "type": "bars"
          }
        ]
      }
    }
  },
  "included": [
    {
      "id": 1,
      "type": "bars",
      "attributes": {
      }
    }
  ]
}
```
When I create a `BarSerializer` without the namespacing, I get what I want as far as the output goes, but I still want my namespacing.

Similarly, when I have a setup like this (without the serializer option):
```
module Blah
  module V1
    module Serializers
      class FooSerializer < AMS
        attribute: id
        has_many :bars
      end
    end
  end
end
```

I get this (note the integer id in the relationships):
```
{
  "data": {
    "id": "1",
    "type": "foos",
    "attributes": {
    },
    "relationships": {
      "bars": {
        "data": [
          {
            "id": 1,
            "type": "bars"
          }
        ]
      }
    }
  },
  "included": [
    {
      "id": 1,
      "type": "bars",
      "attributes": {
      }
    }
  ]
}
```

With luck, I can simply config this. Otherwise, I've got to hack it and then come up with a PR later in the next few weeks.

**Comment by bf4** [comment] 2015-09-17 00:52
Good question :)  Do you think you could write a failing test for what you want?

**Comment by xn** [comment] 2015-09-17 00:54
Yes. Won't happen till next week though. Overloaded ATM.

**Comment by beauby** [comment] 2015-09-21 16:23
Namespacing is currently very poorly handled within AMS. We're working on it.

**Comment by beauby** [comment] 2015-09-22 14:24
However, for your situation, you might find #1157 helpful. There is currently no way to specify a serializer for the include chain passed in the `include` adapter option, and this is kind of by design. Feel free to share any suggestion on how you think the whole thing should behave in #1190.

**Comment by beauby** [comment] 2015-09-24 02:25
After investigating a bit, I find this really weird. Could you try again with master to see if the issue has been fixed?

**Comment by beauby** [comment] 2015-10-08 23:05
I'll close this for now as I can't reproduce the behavior on master. Feel free to reopen if needed.

**Closed by beauby** 2015-10-08 23:05 UTC
Labels: 0.10.x, Needs Bug Verification
