### ISSUE TITLE
Getting ActionView::Template::Error: undefined method `_cache' for NilClass:Class in rspec tests

### ISSUE THREAD

**Issue by daino3** [rails-api/active_model_serializers#1332] opened 2015-11-16 23:19 UTC
I'm getting errors randomly when running my rspec suite in random mode, while rendering the view in my controller tests (for a more integration-like test suite).

I should be tracking what's on master.

```ruby
# Gemfile
gem 'active_model_serializers', git: 'git@github.com:rails-api/active_model_serializers.git'

```

Here's the stack trace:

```
    Failure/Error: get :show, id: exec_firm.id
     ActionView::Template::Error:
       undefined method `_cache' for NilClass:Class
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/cached_serializer.rb:23:in `cached?'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/cached_serializer.rb:11:in `cache_check'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/base.rb:32:in `cache_check'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:59:in `resource_object_for'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:31:in `serializable_hash_for_single_resource'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:16:in `serializable_hash'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:27:in `block in serializable_hash_for_collection'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/array_serializer.rb:6:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/array_serializer.rb:6:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:27:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:27:in `serializable_hash_for_collection'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:14:in `serializable_hash'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:50:in `relationship_value_for'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:39:in `block in resource_relationships'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/associations.rb:97:in `yield'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/associations.rb:97:in `block (2 levels) in associations'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/associations.rb:94:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/associations.rb:94:in `block in associations'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:38:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:38:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:38:in `resource_relationships'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:32:in `serializable_hash_for_single_resource'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/attributes.rb:16:in `serializable_hash'
 # /home/vagrant/.rvm/gems/ruby-2.2.2/bundler/gems/active_model_serializers-526b56e9a629/lib/active_model/serializer/adapter/base.rb:22:in `as_json'
     # ./config/initializers/active_model_serializer.rb:9:in `as_json'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:95:in `jsonify'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:93:in `block in jsonify'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:93:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:93:in `jsonify'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:35:in `encode'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:22:in `encode'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `dump'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/json_dumper.rb:4:in `dump'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/base.rb:94:in `to_json'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/base.rb:78:in `render_variable'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/base.rb:52:in `block in formatted_data'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/base.rb:52:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/base.rb:52:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/base.rb:52:in `formatted_data'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/base.rb:24:in `render_data'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/helpers.rb:5:in `include_gon'
     # ./app/views/layouts/application.html.slim:10:in `_app_views_layouts_application_html_slim__1543260961165707208_35598700'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:23:in `render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/rendering.rb:100:in `_render_template'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/rendering.rb:83:in `render_to_body'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb:25:in `render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:16:in `render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
     # ./app/controllers/firms_controller.rb:30:in `show'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:632:in `process'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:65:in `process'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/devise-3.5.2/lib/devise/test_helpers.rb:19:in `block in process'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/devise-3.5.2/lib/devise/test_helpers.rb:72:in `catch'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/devise-3.5.2/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/devise-3.5.2/lib/devise/test_helpers.rb:19:in `process'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/gon-6.0.1/lib/gon/spec_helpers.rb:15:in `process'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:508:in `get'
     # ./spec/controllers/firms_controller_spec.rb:72:in `block (4 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:11:in `block (3 levels) in <top (required)>'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'
```

Here's my monkey patch: in config/initializers:
```ruby
require 'active_model_serializers'

module ActiveModel
  class Serializer
    # allows me to call as_json on AR serilaizer object
    def as_json(options = {})
      self.class.adapter.new(self).as_json(options)
    end
  end
end
```

**Comment by bf4** [comment] 2015-11-24 17:41
What's the relationship between the error and the monkey patch?

**Comment by daino3** [comment] 2015-11-24 19:13
How do you mean @bf4? The backtrace tells me my monkey-patch is the caller that sets off the error. However, the _cache is in the internals of ARS. 

Here is the serializer:

```ruby
# /firm_serializer.rb
class FirmSerializer < ActiveModel::Serializer
  attributes :id, :name

  belongs_to :clearing_member, serializer: ClearingMemberSerializer
  has_many :accounts, serializer: AccountSerializer
  has_many :contacts, serializer: ContactSerializer
end

# firm_serilaizer_spec.rb
   render_views

    describe 'GET #show' do
      let(:exec_firm) { FactoryGirl.create(:executing_firm, :with_contacts) }

      it 'retrieves the firm and its contacts' do
        allow(FirmSerializer).to receive(:new).and_call_original

        get :show, id: firm.id

        firm = assigns(:firm)

        expect(firm).to eq(firm)
        expect(assigns(:contacts)).to eq(firm.contacts)
      end

      it 'loads the appropriate relationships for optimized performance' do
        expect(FirmSerializer).to receive(:new).and_call_original

        get :show, id: firm.id

        expect(firm.association(:contacts).loaded?).to be true
        expect(firm.association(:executing_firms).loaded?).to be true
        expect(firm.executing_firms.first.association(:contacts).loaded?).to be true
        expect(firm.executing_firms.first.association(:accounts).loaded?).to be true
        expect(firm.executing_firms.first.accounts.first.association(:traders).loaded?).to be true
      end
    end

# firm_controller.rb
  def show
    firm = Firm.find(params[:id])
    @contacts = firm.contacts
    @firm = ExecutingFirm.includes(:clearing_member, :contacts, accounts: [:traders]).find(params[:id])
    firm_as_json =  FirmSerializer.new(firm).as_json
  
    gon.firm = firm_as_json

    respond_to do |format|
      format.html
    end
  end

```
I'll see if I can reproduce this error in a gist or something too.

**Comment by bf4** [comment] 2015-11-24 19:16
Sounds like the monkeypatch is the problem. It's also not a recommended usage, which is why that interface doesn't exist.   I'm pretty sure you don't need it.  Just use what AMS provides: SerializableResource.

Are you responding to an html request with json?  That would be surprising behavior.

I'm going to close this since it appears the problem is in your monkey patch.

Please reopen if you can remove the monkeypatch and share failing code I can run.

**Closed by bf4** 2015-11-24 19:16 UTC
Labels: Needs Bug Verification, Needs Submitter Response
