### ISSUE TITLE
Versioning ActiveModel::Serializer

### ISSUE THREAD

**Issue by jeromeboe** [rails-api/active_model_serializers#671] opened 2014-10-02 11:50 UTC
I'm facing some issues with versioning.

**Controllers**

In `app/controllers/v1/contracts_controller.rb`
```ruby
module V1
    class ContractsController < ApiController

        def index
            @contracts = Contract.all
            render json: @contracts
        end

    end
end
```

In `app/controllers/v2/contracts_controller.rb`
```ruby
module V2
    class ContractsController < ApiController

        def index
            @contracts = Contract.all
            render json: @contracts
        end

    end
end
```

**Serializers**

In `app/serializers/v1/contract_serializer.rb`
```ruby
class ContractSerializer < ActiveModel::Serializer
    attributes :id
end
```

In `app/serializers/v2/contract_serializer.rb`
```ruby
class ContractSerializer < ActiveModel::Serializer
    attributes :id, :name
end
```

Whether I call the route `/v1/contracts` or `/v2/contracts`, the rendered json include the contract name, which means that the serializer in v2 seems to be always called.

FYI, I added `config.autoload_paths += Dir[Rails.root.join('app', 'serializers', '**/')]` in `config/application.rb`

**Comment by brancusi** [comment] 2015-01-16 23:06
+1

**Comment by chadwtaylor** [comment] 2015-01-30 14:41
+1

**Comment by gwagener** [comment] 2015-03-11 01:17
Have you tried adding modules `V1` and `V2` to your serializers so they match the directory structure? I did something similar and I can't remember if I then had to explicitly specify the serializer in the `render` call, but I got it working.

**Comment by formigarafa** [comment] 2015-04-10 22:49
as @d3chapma said lots of versioning issues have being closed and mostly rejected (if not all). And I believe that there is something missing in all discussions I have seen so far: who defines the resource name?

After all the AMS is responsible to serializer a model for a controller. However, Who owns the namespace? What if the model is also namespaced? Should we search for a serializer accordingly with the controller namespace/name or model namespace/name?

Imagine a admin/v1/media_controller rendering media/photo models.

what is the path resolution for these serializer?

media/photo serializer?
admin/v1/media/serializer?
or even admin/v1/media/photo serializer?

I believe there is one piece missing in this puzzle. (like a view object or a presenter)

controller -> *something* -> serializer -> model
or
controller -> serializer -> * something * -> model

**Comment by jejacks0n** [comment] 2015-04-10 23:06
The primary issue with 0.8 and 0.9 was that it would go through the model to figure out what controller is used. I worked this out in a fork, which is not production worthy, but it's mostly there in 0.10 -- the only problem was that the controller options and association options (eg. `has_many`, `belongs_to`) don't have parity. I adjusted that so they are the same in terms of `has_many` being able to use `each_serializer: Api::V1::UserSerializer` as well as specify an array serializer if you needed to override that with `serializer: Api::V1::UserCollectionSerializer`. This worked out pretty well, but felt really bad that so many overrides were required.

**Comment by bf4** [comment] 2015-08-21 00:12
@jeromeboe Specifically here the issue is Ruby.  

We want two classes, one for each version, to subclass Serializer.  

We can do that with `module V1; class ContractSerializer < ActiveModel::Serializer; end` (or `class V1:: ContractSerializer < ActiveModel::Serializer` if the V1 module has already been loaded), the same for V2.

You'll need `render @blog, each_serializer: V1::ContractSerializer`.

It might be nice for AMS to get the right namespaced serializer from a namespaced controller. That shouldn't be too hard of a PR, I don't think.

**Comment by joaomdmoura** [comment] 2015-08-21 05:15
Hey everyone, this is open for a while,
As you noticed we have discussed versioning on other issues and PR's as well, and 
I'm glad to read so really nice thought from all of you.

On 0.10.x, the best option would be to specify the serializer as @bf4 just posted above.

@jeromeboe it seems there are some pieces of code missing on what you posted, there are no namespace declared neither we know what version you are using.

I'm closing this one for now, but if any of you end up having other question or problems, please, make yourself comfortable to reach us through github, IRC or whatever, I'll be glad to help.

**Closed by joaomdmoura** 2015-08-21 05:15 UTC
